using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

public static class PathCoverLevelGeneratorAlgorithm
{
    private static readonly ArrowDirection[] Directions =
    {
        ArrowDirection.Up,
        ArrowDirection.Down,
        ArrowDirection.Left,
        ArrowDirection.Right
    };

    public static LevelData Generate(EditorGenerationRequest request)
    {
        GenerationContext context = BuildContext(request);
        if (context == null)
        {
            return null;
        }

        context.Stopwatch.Start();

        List<int> arrowCountAttempts = BuildArrowCountAttempts(context);
        for (int i = 0; i < arrowCountAttempts.Count; i++)
        {
            if (context.ShouldStop())
            {
                break;
            }

            context.TargetArrowCount = arrowCountAttempts[i];
            if (TryGenerateGreedyPathCover(context, out List<PathCandidate> greedyPaths, out List<DirectionAssignment> greedyAssignments, out DependencyGraph greedyGraph))
            {
                context.Stopwatch.Stop();

                LevelData levelData = BuildLevelData(context, greedyPaths, greedyAssignments);
                if (!ValidateFinalLevel(context, levelData, out List<DependencyData> dependencies, out List<int> solutionOrder))
                {
                    context.Fail("internal final validation rejected the greedy path cover");
                    LogFailure(context);
                    return null;
                }

                levelData.dependencies = dependencies;
                levelData.solutionOrder = solutionOrder;
                levelData.notes = $"Generated by greedy path-cover DAG generator. Seed: {context.Seed}. Arrow count: {greedyPaths.Count}. Requested range: {context.RequestedMinArrowCount}-{context.RequestedMaxArrowCount}. Search frames: {context.SearchFrames}. Greedy attempts: {context.GreedyAttempts}. Direction frames: {context.DirectionSearchFrames}. Candidate checks: {context.CandidateChecks}.";
                return levelData;
            }

            if (!context.ShouldRunBacktrackingSearch())
            {
                continue;
            }

            SearchState initialState = new SearchState
            {
                FreeCells = new HashSet<Cell>(context.ShapeCells),
                PlacedPaths = new List<PathCandidate>()
            };

            if (SearchPathCover(initialState, context, out List<PathCandidate> paths, out List<DirectionAssignment> assignments, out DependencyGraph graph))
            {
                context.Stopwatch.Stop();

                LevelData levelData = BuildLevelData(context, paths, assignments);
                if (!ValidateFinalLevel(context, levelData, out List<DependencyData> dependencies, out List<int> solutionOrder))
                {
                    context.Fail("internal final validation rejected the path cover");
                    LogFailure(context);
                    return null;
                }

                levelData.dependencies = dependencies;
                levelData.solutionOrder = solutionOrder;
                levelData.notes = $"Generated by path-cover DAG generator. Seed: {context.Seed}. Arrow count: {paths.Count}. Requested range: {context.RequestedMinArrowCount}-{context.RequestedMaxArrowCount}. Search frames: {context.SearchFrames}. Direction frames: {context.DirectionSearchFrames}. Candidate checks: {context.CandidateChecks}.";
                return levelData;
            }
        }

        context.Stopwatch.Stop();
        if (string.IsNullOrWhiteSpace(context.FailureReason))
        {
            context.Fail("no path cover and acyclic direction assignment found under current limits");
        }

        LogFailure(context);
        return null;
    }

    private static GenerationContext BuildContext(EditorGenerationRequest request)
    {
        if (request == null)
        {
            Debug.LogWarning("Path-cover generation failed: request is null.");
            return null;
        }

        if (request.gridSize <= 0)
        {
            Debug.LogWarning("Path-cover generation failed: grid size must be positive.");
            return null;
        }

        if (request.minArrowLength <= 0 || request.maxArrowLength <= 0 || request.minArrowLength > request.maxArrowLength)
        {
            Debug.LogWarning("Path-cover generation failed: arrow length range is invalid.");
            return null;
        }

        int requestedMinArrowCount;
        int requestedMaxArrowCount;
        if (request.minArrowCount > 0 || request.maxArrowCount > 0)
        {
            requestedMinArrowCount = Mathf.Max(0, Mathf.Min(request.minArrowCount, request.maxArrowCount));
            requestedMaxArrowCount = Mathf.Max(requestedMinArrowCount, Mathf.Max(request.minArrowCount, request.maxArrowCount));
        }
        else
        {
            requestedMinArrowCount = Mathf.Max(0, request.targetArrowCount);
            requestedMaxArrowCount = requestedMinArrowCount;
        }

        HashSet<Cell> shapeCells = new HashSet<Cell>();
        if (request.paintedCells != null)
        {
            for (int i = 0; i < request.paintedCells.Count; i++)
            {
                GridPositionData paintedCell = request.paintedCells[i];
                if (paintedCell == null)
                {
                    continue;
                }

                Cell cell = new Cell(paintedCell.x, paintedCell.y);
                if (!IsInsideBoard(cell, request.gridSize, request.gridSize))
                {
                    Debug.LogWarning($"Path-cover generation failed: painted cell ({paintedCell.x}, {paintedCell.y}) is outside the board.");
                    return null;
                }

                shapeCells.Add(cell);
            }
        }

        if (shapeCells.Count == 0)
        {
            Debug.LogWarning("Path-cover generation failed: paint at least one shape cell before generating.");
            return null;
        }

        int lengthMinimumArrowCount = CeilDiv(shapeCells.Count, request.maxArrowLength);
        int lengthMaximumArrowCount = shapeCells.Count / request.minArrowLength;
        int effectiveMinArrowCount = Math.Max(requestedMinArrowCount, lengthMinimumArrowCount);
        int effectiveMaxArrowCount = Math.Min(requestedMaxArrowCount, lengthMaximumArrowCount);

        if (effectiveMinArrowCount > effectiveMaxArrowCount)
        {
            Debug.LogWarning($"Path-cover generation failed: {shapeCells.Count} painted cells cannot fit arrow count range {requestedMinArrowCount}-{requestedMaxArrowCount} with length range {request.minArrowLength}-{request.maxArrowLength}.");
            return null;
        }

        int requestedCandidateCap = Mathf.Max(0, request.maxCandidatesPerSearchState);
        int adaptiveCandidateCap = request.gridSize >= 9 ? 768 : request.gridSize >= 7 ? 1024 : 1536;
        int adaptivePivotArmCap = request.gridSize >= 9 ? 128 : request.gridSize >= 7 ? 176 : 240;
        int requestedSearchFrames = Mathf.Max(0, request.maxSearchIterations);
        int adaptiveSearchFrames = request.gridSize >= 9 ? 1500000 : request.gridSize >= 7 ? 750000 : 250000;
        int greedyAttemptCount = request.gridSize >= 9 ? 96 : request.gridSize >= 7 ? 64 : 32;
        float requestedSeconds = Mathf.Max(0f, request.maxGenerationSeconds);
        float adaptiveSeconds = request.gridSize >= 9 ? 20f : request.gridSize >= 7 ? 12f : 8f;
        int seed = request.useRandomSeed ? request.randomSeed : Environment.TickCount;

        return new GenerationContext
        {
            BoardWidth = request.gridSize,
            BoardHeight = request.gridSize,
            RequestedMinArrowCount = requestedMinArrowCount,
            RequestedMaxArrowCount = requestedMaxArrowCount,
            EffectiveMinArrowCount = effectiveMinArrowCount,
            EffectiveMaxArrowCount = effectiveMaxArrowCount,
            MinArrowLength = request.minArrowLength,
            MaxArrowLength = request.maxArrowLength,
            Lives = request.lives,
            Seed = seed,
            ShapeCells = shapeCells,
            Random = new System.Random(seed),
            RequestedMaxSearchFrames = requestedSearchFrames,
            MaxSearchFrames = requestedSearchFrames == 0 ? 0 : Math.Max(requestedSearchFrames, adaptiveSearchFrames),
            MaxCandidatesPerState = requestedCandidateCap == 0 ? adaptiveCandidateCap : Math.Max(requestedCandidateCap, adaptiveCandidateCap),
            MaxPivotArms = adaptivePivotArmCap,
            MaxGreedyAttemptsPerArrowCount = greedyAttemptCount,
            RequestedMaxGenerationSeconds = requestedSeconds,
            MaxGenerationSeconds = requestedSeconds <= 0f ? 0f : Mathf.Max(requestedSeconds, adaptiveSeconds),
            Stopwatch = new System.Diagnostics.Stopwatch()
        };
    }

    private static List<int> BuildArrowCountAttempts(GenerationContext context)
    {
        List<int> attempts = new List<int>();
        for (int count = context.EffectiveMinArrowCount; count <= context.EffectiveMaxArrowCount; count++)
        {
            attempts.Add(count);
        }

        float preferredLength = (context.MinArrowLength + context.MaxArrowLength) * 0.5f;
        float preferredCount = context.ShapeCells.Count / Mathf.Max(1f, preferredLength);
        Shuffle(attempts, context.Random);
        attempts.Sort((a, b) =>
        {
            float aDistance = Mathf.Abs(a - preferredCount);
            float bDistance = Mathf.Abs(b - preferredCount);
            int distanceCompare = aDistance.CompareTo(bDistance);
            return distanceCompare != 0 ? distanceCompare : a.CompareTo(b);
        });

        return attempts;
    }

    private static bool SearchPathCover(
        SearchState state,
        GenerationContext context,
        out List<PathCandidate> resultPaths,
        out List<DirectionAssignment> resultAssignments,
        out DependencyGraph resultGraph)
    {
        resultPaths = null;
        resultAssignments = null;
        resultGraph = null;

        if (context.ShouldStop())
        {
            return false;
        }

        context.SearchFrames++;
        int remainingPathCount = context.TargetArrowCount - state.PlacedPaths.Count;

        if (remainingPathCount == 0)
        {
            if (state.FreeCells.Count != 0)
            {
                return false;
            }

            List<PathCandidate> paths = CloneAndAssignPathIds(state.PlacedPaths);
            if (!TryAssignDirections(context, paths, out resultAssignments, out resultGraph))
            {
                return false;
            }

            resultPaths = paths;
            return true;
        }

        if (RemainingFeasibilityFails(context, state.FreeCells, remainingPathCount))
        {
            return false;
        }

        Cell pivot = ChoosePivotCell(context, state.FreeCells);
        List<PathCandidate> candidates = GeneratePathCandidatesForPivot(context, state, pivot);
        context.CandidateChecks += candidates.Count;
        if (context.ShouldStop())
        {
            return false;
        }

        for (int i = 0; i < candidates.Count; i++)
        {
            if (context.ShouldStop())
            {
                return false;
            }

            PathCandidate candidate = candidates[i];
            HashSet<Cell> nextFreeCells = new HashSet<Cell>(state.FreeCells);
            bool removedAllCandidateCells = true;
            for (int cellIndex = 0; cellIndex < candidate.Cells.Count; cellIndex++)
            {
                if (!nextFreeCells.Remove(candidate.Cells[cellIndex]))
                {
                    removedAllCandidateCells = false;
                    break;
                }
            }

            if (!removedAllCandidateCells)
            {
                continue;
            }

            int nextRemainingPathCount = remainingPathCount - 1;
            if (RemainingFeasibilityFails(context, nextFreeCells, nextRemainingPathCount))
            {
                continue;
            }

            state.PlacedPaths.Add(candidate);
            HashSet<Cell> previousFreeCells = state.FreeCells;
            state.FreeCells = nextFreeCells;

            if (SearchPathCover(state, context, out resultPaths, out resultAssignments, out resultGraph))
            {
                return true;
            }

            state.FreeCells = previousFreeCells;
            state.PlacedPaths.RemoveAt(state.PlacedPaths.Count - 1);
        }

        return false;
    }

    private static bool TryGenerateGreedyPathCover(
        GenerationContext context,
        out List<PathCandidate> resultPaths,
        out List<DirectionAssignment> resultAssignments,
        out DependencyGraph resultGraph)
    {
        resultPaths = null;
        resultAssignments = null;
        resultGraph = null;

        for (int attempt = 0; attempt < context.MaxGreedyAttemptsPerArrowCount; attempt++)
        {
            if (context.ShouldStop())
            {
                return false;
            }

            context.GreedyAttempts++;
            SearchState state = new SearchState
            {
                FreeCells = new HashSet<Cell>(context.ShapeCells),
                PlacedPaths = new List<PathCandidate>()
            };

            bool failed = false;
            while (state.PlacedPaths.Count < context.TargetArrowCount)
            {
                if (context.ShouldStop())
                {
                    return false;
                }

                int remainingPathCount = context.TargetArrowCount - state.PlacedPaths.Count;
                if (RemainingFeasibilityFails(context, state.FreeCells, remainingPathCount))
                {
                    failed = true;
                    break;
                }

                Cell pivot = ChoosePivotCell(context, state.FreeCells);
                List<PathCandidate> candidates = GeneratePathCandidatesForPivot(context, state, pivot);
                context.CandidateChecks += candidates.Count;

                if (context.ShouldStop())
                {
                    return false;
                }

                PathCandidate selectedCandidate = null;
                HashSet<Cell> selectedRemainingCells = null;
                for (int i = 0; i < candidates.Count; i++)
                {
                    PathCandidate candidate = candidates[i];
                    if (!CandidateFitsCurrentLengthWindow(context, state.FreeCells.Count, remainingPathCount, candidate))
                    {
                        continue;
                    }

                    if (!PathHasAnyLegalTipDirection(context, candidate))
                    {
                        continue;
                    }

                    HashSet<Cell> nextFreeCells = RemoveCandidateCells(state.FreeCells, candidate);
                    if (nextFreeCells == null)
                    {
                        continue;
                    }

                    if (RemainingFeasibilityFails(context, nextFreeCells, remainingPathCount - 1))
                    {
                        continue;
                    }

                    selectedCandidate = candidate;
                    selectedRemainingCells = nextFreeCells;
                    break;
                }

                if (selectedCandidate == null)
                {
                    failed = true;
                    break;
                }

                state.PlacedPaths.Add(selectedCandidate);
                state.FreeCells = selectedRemainingCells;
            }

            if (failed || state.FreeCells.Count != 0 || state.PlacedPaths.Count != context.TargetArrowCount)
            {
                continue;
            }

            List<PathCandidate> paths = CloneAndAssignPathIds(state.PlacedPaths);
            if (!TryAssignDirections(context, paths, out resultAssignments, out resultGraph))
            {
                continue;
            }

            resultPaths = paths;
            return true;
        }

        return false;
    }

    private static List<PathCandidate> GeneratePathCandidatesForPivot(GenerationContext context, SearchState state, Cell pivot)
    {
        List<List<Cell>> arms = BuildPivotArms(context, state.FreeCells, pivot);
        List<PathCandidate> candidates = new List<PathCandidate>();
        HashSet<string> seenKeys = new HashSet<string>();

        for (int i = 0; i < arms.Count; i++)
        {
            if (context.ShouldStop())
            {
                return candidates;
            }

            List<Cell> arm = arms[i];
            if (arm.Count >= context.MinArrowLength && arm.Count <= context.MaxArrowLength)
            {
                AddPathCandidate(arm, candidates, seenKeys);
            }
        }

        for (int firstIndex = 0; firstIndex < arms.Count; firstIndex++)
        {
            if (context.ShouldStop())
            {
                return candidates;
            }

            List<Cell> firstArm = arms[firstIndex];
            if (firstArm.Count <= 1)
            {
                continue;
            }

            for (int secondIndex = firstIndex + 1; secondIndex < arms.Count; secondIndex++)
            {
                if (context.ShouldStop())
                {
                    return candidates;
                }

                List<Cell> secondArm = arms[secondIndex];
                if (secondArm.Count <= 1)
                {
                    continue;
                }

                int combinedLength = firstArm.Count + secondArm.Count - 1;
                if (combinedLength < context.MinArrowLength || combinedLength > context.MaxArrowLength)
                {
                    continue;
                }

                if (!ArmsOnlyIntersectAtPivot(firstArm, secondArm))
                {
                    continue;
                }

                List<Cell> combinedPath = new List<Cell>(combinedLength);
                for (int i = firstArm.Count - 1; i >= 0; i--)
                {
                    combinedPath.Add(firstArm[i]);
                }

                for (int i = 1; i < secondArm.Count; i++)
                {
                    combinedPath.Add(secondArm[i]);
                }

                AddPathCandidate(combinedPath, candidates, seenKeys);
            }
        }

        Shuffle(candidates, context.Random);
        SortPathCandidates(candidates, state, context);

        if (context.MaxCandidatesPerState > 0 && candidates.Count > context.MaxCandidatesPerState)
        {
            candidates.RemoveRange(context.MaxCandidatesPerState, candidates.Count - context.MaxCandidatesPerState);
        }

        return candidates;
    }

    private static List<List<Cell>> BuildPivotArms(GenerationContext context, HashSet<Cell> freeCells, Cell pivot)
    {
        List<List<Cell>> arms = new List<List<Cell>>();
        List<Cell> currentPath = new List<Cell> { pivot };
        HashSet<Cell> currentPathSet = new HashSet<Cell> { pivot };

        CollectPivotArms(context, freeCells, currentPath, currentPathSet, arms);
        return arms;
    }

    private static void CollectPivotArms(
        GenerationContext context,
        HashSet<Cell> freeCells,
        List<Cell> currentPath,
        HashSet<Cell> currentPathSet,
        List<List<Cell>> arms)
    {
        if (arms.Count >= context.MaxPivotArms)
        {
            return;
        }

        if (context.ShouldStop())
        {
            return;
        }

        arms.Add(new List<Cell>(currentPath));

        if (currentPath.Count >= context.MaxArrowLength)
        {
            return;
        }

        Cell head = currentPath[currentPath.Count - 1];
        List<Cell> neighbors = GetFreeUnusedNeighbors(head, freeCells, currentPathSet);
        Shuffle(neighbors, context.Random);
        neighbors.Sort((a, b) =>
        {
            int degreeCompare = CountFreeNeighbors(a, freeCells, currentPathSet).CompareTo(CountFreeNeighbors(b, freeCells, currentPathSet));
            if (degreeCompare != 0)
            {
                return degreeCompare;
            }

            return DistanceToBoardEdge(a, context.BoardWidth, context.BoardHeight).CompareTo(DistanceToBoardEdge(b, context.BoardWidth, context.BoardHeight));
        });

        for (int i = 0; i < neighbors.Count; i++)
        {
            if (arms.Count >= context.MaxPivotArms || context.ShouldStop())
            {
                return;
            }

            Cell next = neighbors[i];
            currentPath.Add(next);
            currentPathSet.Add(next);
            CollectPivotArms(context, freeCells, currentPath, currentPathSet, arms);
            currentPathSet.Remove(next);
            currentPath.RemoveAt(currentPath.Count - 1);
        }
    }

    private static bool TryAssignDirections(
        GenerationContext context,
        List<PathCandidate> paths,
        out List<DirectionAssignment> assignments,
        out DependencyGraph graph)
    {
        assignments = null;
        graph = new DependencyGraph();

        Dictionary<int, PathCandidate> pathsById = new Dictionary<int, PathCandidate>();
        Dictionary<int, List<DirectionOption>> optionsByArrowId = new Dictionary<int, List<DirectionOption>>();
        for (int i = 0; i < paths.Count; i++)
        {
            if (context.ShouldStop())
            {
                return false;
            }

            PathCandidate path = paths[i];
            pathsById[path.Id] = path;
            graph.AddNode(path.Id);

            List<DirectionOption> options = BuildDirectionOptions(context, path, paths);
            if (context.ShouldStop())
            {
                return false;
            }

            if (options.Count == 0)
            {
                return false;
            }

            optionsByArrowId[path.Id] = options;
        }

        Dictionary<int, DirectionAssignment> assignedByArrowId = new Dictionary<int, DirectionAssignment>();
        if (!SearchDirectionAssignments(context, pathsById, optionsByArrowId, assignedByArrowId, graph, out assignments, out graph))
        {
            return false;
        }

        return assignments.Count == paths.Count && graph.IsAcyclic();
    }

    private static bool SearchDirectionAssignments(
        GenerationContext context,
        Dictionary<int, PathCandidate> pathsById,
        Dictionary<int, List<DirectionOption>> optionsByArrowId,
        Dictionary<int, DirectionAssignment> assignedByArrowId,
        DependencyGraph graph,
        out List<DirectionAssignment> resultAssignments,
        out DependencyGraph resultGraph)
    {
        resultAssignments = null;
        resultGraph = null;

        if (context.ShouldStop())
        {
            return false;
        }

        context.DirectionSearchFrames++;

        if (assignedByArrowId.Count == pathsById.Count)
        {
            resultAssignments = new List<DirectionAssignment>(assignedByArrowId.Values);
            resultAssignments.Sort((a, b) => a.ArrowId.CompareTo(b.ArrowId));
            resultGraph = graph;
            return true;
        }

        int selectedArrowId = -1;
        List<DirectionOption> selectedOptions = null;
        foreach (int arrowId in pathsById.Keys)
        {
            if (context.ShouldStop())
            {
                return false;
            }

            if (assignedByArrowId.ContainsKey(arrowId))
            {
                continue;
            }

            List<DirectionOption> availableOptions = GetAssignableDirectionOptions(optionsByArrowId[arrowId], assignedByArrowId, assignedByArrowId.Count == 0);
            if (availableOptions.Count == 0)
            {
                return false;
            }

            if (selectedOptions == null || availableOptions.Count < selectedOptions.Count)
            {
                selectedArrowId = arrowId;
                selectedOptions = availableOptions;
            }
        }

        if (selectedArrowId < 0 || selectedOptions == null)
        {
            return false;
        }

        Shuffle(selectedOptions, context.Random);
        SortDirectionOptions(selectedOptions, assignedByArrowId.Count == 0);

        for (int i = 0; i < selectedOptions.Count; i++)
        {
            if (context.ShouldStop())
            {
                return false;
            }

            DirectionOption option = selectedOptions[i];
            DependencyGraph nextGraph = graph.Clone();
            foreach (int blockerArrowId in option.BlockerIds)
            {
                nextGraph.AddEdge(blockerArrowId, selectedArrowId);
            }

            if (!nextGraph.IsAcyclic())
            {
                continue;
            }

            assignedByArrowId[selectedArrowId] = new DirectionAssignment
            {
                ArrowId = selectedArrowId,
                TipCell = option.TipCell,
                Direction = option.Direction,
                BlockerIds = new HashSet<int>(option.BlockerIds)
            };

            if (SearchDirectionAssignments(context, pathsById, optionsByArrowId, assignedByArrowId, nextGraph, out resultAssignments, out resultGraph))
            {
                return true;
            }

            assignedByArrowId.Remove(selectedArrowId);
        }

        return false;
    }

    private static List<DirectionOption> BuildDirectionOptions(GenerationContext context, PathCandidate path, List<PathCandidate> allPaths)
    {
        List<DirectionOption> options = new List<DirectionOption>();
        List<Cell> leaves = GetPathLeaves(path);

        for (int leafIndex = 0; leafIndex < leaves.Count; leafIndex++)
        {
            if (context.ShouldStop())
            {
                return options;
            }

            Cell leaf = leaves[leafIndex];
            for (int directionIndex = 0; directionIndex < Directions.Length; directionIndex++)
            {
                if (context.ShouldStop())
                {
                    return options;
                }

                ArrowDirection direction = Directions[directionIndex];
                if (ExitRayIntersectsCells(leaf, direction, path.CellSet, context.BoardWidth, context.BoardHeight))
                {
                    continue;
                }

                HashSet<int> blockers = FindBlockingArrowIds(context, allPaths, path.Id, leaf, direction);
                options.Add(new DirectionOption
                {
                    TipCell = leaf,
                    Direction = direction,
                    BlockerIds = blockers
                });
            }
        }

        return options;
    }

    private static List<DirectionOption> GetAssignableDirectionOptions(
        List<DirectionOption> options,
        Dictionary<int, DirectionAssignment> assignedByArrowId,
        bool firstAssignment)
    {
        List<DirectionOption> assignable = new List<DirectionOption>();
        for (int i = 0; i < options.Count; i++)
        {
            DirectionOption option = options[i];
            if (firstAssignment && option.BlockerIds.Count > 0)
            {
                continue;
            }

            bool allBlockersAlreadyAssigned = true;
            foreach (int blockerArrowId in option.BlockerIds)
            {
                if (!assignedByArrowId.ContainsKey(blockerArrowId))
                {
                    allBlockersAlreadyAssigned = false;
                    break;
                }
            }

            if (allBlockersAlreadyAssigned)
            {
                assignable.Add(option);
            }
        }

        return assignable;
    }

    private static LevelData BuildLevelData(GenerationContext context, List<PathCandidate> paths, List<DirectionAssignment> assignments)
    {
        Dictionary<int, DirectionAssignment> assignmentByArrowId = new Dictionary<int, DirectionAssignment>();
        for (int i = 0; i < assignments.Count; i++)
        {
            assignmentByArrowId[assignments[i].ArrowId] = assignments[i];
        }

        LevelData levelData = new LevelData
        {
            gridSize = context.BoardWidth,
            width = context.BoardWidth,
            height = context.BoardHeight,
            targetArrowCount = paths.Count,
            minArrowCount = context.RequestedMinArrowCount,
            maxArrowCount = context.RequestedMaxArrowCount,
            minArrowLength = context.MinArrowLength,
            maxArrowLength = context.MaxArrowLength,
            lives = context.Lives,
            arrows = new List<ArrowData>(),
            shapeCells = ToGridPositions(ToSortedCells(context.ShapeCells)),
            dependencies = new List<DependencyData>(),
            solutionOrder = new List<int>(),
            createdAt = DateTime.UtcNow.ToString("o")
        };

        paths.Sort((a, b) => a.Id.CompareTo(b.Id));
        for (int i = 0; i < paths.Count; i++)
        {
            PathCandidate path = paths[i];
            DirectionAssignment assignment = assignmentByArrowId[path.Id];
            levelData.arrows.Add(new ArrowData
            {
                arrowId = path.Id,
                length = path.Cells.Count,
                occupiedCells = ToGridPositions(path.Cells),
                tipCell = new GridPositionData(assignment.TipCell.X, assignment.TipCell.Y),
                tipDirection = assignment.Direction,
                isSolved = false
            });
        }

        return levelData;
    }

    private static bool ValidateFinalLevel(
        GenerationContext context,
        LevelData levelData,
        out List<DependencyData> dependencies,
        out List<int> solutionOrder)
    {
        dependencies = null;
        solutionOrder = null;

        if (levelData == null || levelData.arrows == null)
        {
            return false;
        }

        if (levelData.arrows.Count < context.RequestedMinArrowCount || levelData.arrows.Count > context.RequestedMaxArrowCount)
        {
            return false;
        }

        Dictionary<int, RuntimeArrow> arrowsById = new Dictionary<int, RuntimeArrow>();
        HashSet<Cell> coveredCells = new HashSet<Cell>();
        for (int i = 0; i < levelData.arrows.Count; i++)
        {
            if (!TryCreateRuntimeArrow(context, levelData.arrows[i], out RuntimeArrow arrow))
            {
                return false;
            }

            if (arrowsById.ContainsKey(arrow.Id))
            {
                return false;
            }

            arrowsById.Add(arrow.Id, arrow);

            for (int cellIndex = 0; cellIndex < arrow.PathCells.Count; cellIndex++)
            {
                Cell cell = arrow.PathCells[cellIndex];
                if (!context.ShapeCells.Contains(cell) || !coveredCells.Add(cell))
                {
                    return false;
                }
            }

            if (ExitRayIntersectsCells(arrow.TipCell, arrow.Direction, arrow.CellSet, context.BoardWidth, context.BoardHeight))
            {
                return false;
            }
        }

        if (coveredCells.Count != context.ShapeCells.Count)
        {
            return false;
        }

        DependencyGraph graph = new DependencyGraph();
        foreach (int arrowId in arrowsById.Keys)
        {
            graph.AddNode(arrowId);
        }

        foreach (RuntimeArrow blockedArrow in arrowsById.Values)
        {
            foreach (RuntimeArrow blockerArrow in arrowsById.Values)
            {
                if (blockerArrow.Id == blockedArrow.Id)
                {
                    continue;
                }

                if (ExitRayIntersectsCells(blockedArrow.TipCell, blockedArrow.Direction, blockerArrow.CellSet, context.BoardWidth, context.BoardHeight))
                {
                    graph.AddEdge(blockerArrow.Id, blockedArrow.Id);
                }
            }
        }

        if (!graph.IsAcyclic())
        {
            return false;
        }

        dependencies = graph.ToDependencyData();
        solutionOrder = graph.TopologicalSort();
        return solutionOrder.Count == arrowsById.Count;
    }

    private static bool TryCreateRuntimeArrow(GenerationContext context, ArrowData arrowData, out RuntimeArrow arrow)
    {
        arrow = null;
        if (arrowData == null ||
            arrowData.occupiedCells == null ||
            arrowData.occupiedCells.Count < context.MinArrowLength ||
            arrowData.occupiedCells.Count > context.MaxArrowLength ||
            arrowData.tipCell == null ||
            arrowData.tipDirection == ArrowDirection.None)
        {
            return false;
        }

        List<Cell> pathCells = new List<Cell>();
        HashSet<Cell> pathSet = new HashSet<Cell>();
        for (int i = 0; i < arrowData.occupiedCells.Count; i++)
        {
            GridPositionData gridCell = arrowData.occupiedCells[i];
            if (gridCell == null)
            {
                return false;
            }

            Cell cell = new Cell(gridCell.x, gridCell.y);
            if (!IsInsideBoard(cell, context.BoardWidth, context.BoardHeight) || !pathSet.Add(cell))
            {
                return false;
            }

            if (i > 0 && ManhattanDistance(pathCells[i - 1], cell) != 1)
            {
                return false;
            }

            pathCells.Add(cell);
        }

        Cell tipCell = new Cell(arrowData.tipCell.x, arrowData.tipCell.y);
        bool tipIsFirstLeaf = pathCells[0] == tipCell;
        bool tipIsLastLeaf = pathCells[pathCells.Count - 1] == tipCell;
        if (!tipIsFirstLeaf && !tipIsLastLeaf)
        {
            return false;
        }

        arrow = new RuntimeArrow
        {
            Id = arrowData.arrowId,
            PathCells = pathCells,
            CellSet = pathSet,
            TipCell = tipCell,
            Direction = arrowData.tipDirection
        };
        return true;
    }

    private static bool RemainingFeasibilityFails(GenerationContext context, HashSet<Cell> remainingCells, int remainingPathCount)
    {
        if (remainingPathCount == 0)
        {
            return remainingCells.Count != 0;
        }

        int remainingCellCount = remainingCells.Count;
        if (remainingCellCount < remainingPathCount * context.MinArrowLength)
        {
            return true;
        }

        if (remainingCellCount > remainingPathCount * context.MaxArrowLength)
        {
            return true;
        }

        List<List<Cell>> components = GetConnectedComponents(remainingCells);
        int minimumNeeded = 0;
        int maximumPossible = 0;
        for (int i = 0; i < components.Count; i++)
        {
            int componentSize = components[i].Count;
            int componentMinimum = CeilDiv(componentSize, context.MaxArrowLength);
            int componentMaximum = componentSize / context.MinArrowLength;
            if (componentMinimum > componentMaximum)
            {
                return true;
            }

            minimumNeeded += componentMinimum;
            maximumPossible += componentMaximum;
        }

        return minimumNeeded > remainingPathCount || maximumPossible < remainingPathCount;
    }

    private static Cell ChoosePivotCell(GenerationContext context, HashSet<Cell> freeCells)
    {
        List<List<Cell>> components = GetConnectedComponents(freeCells);
        components.Sort((a, b) => a.Count.CompareTo(b.Count));
        List<Cell> component = components[0];

        Cell bestCell = component[0];
        int bestScore = int.MaxValue;
        for (int i = 0; i < component.Count; i++)
        {
            Cell cell = component[i];
            int degree = CountFreeNeighbors(cell, freeCells, null);
            int edgeDistance = DistanceToBoardEdge(cell, context.BoardWidth, context.BoardHeight);
            int score = degree * 100 + edgeDistance * 8 + context.Random.Next(8);
            if (score < bestScore)
            {
                bestScore = score;
                bestCell = cell;
            }
        }

        return bestCell;
    }

    private static List<List<Cell>> GetConnectedComponents(HashSet<Cell> cells)
    {
        List<List<Cell>> components = new List<List<Cell>>();
        HashSet<Cell> unvisited = new HashSet<Cell>(cells);
        Queue<Cell> queue = new Queue<Cell>();

        while (unvisited.Count > 0)
        {
            Cell start = FirstCell(unvisited);
            unvisited.Remove(start);
            queue.Enqueue(start);

            List<Cell> component = new List<Cell>();
            component.Add(start);

            while (queue.Count > 0)
            {
                Cell current = queue.Dequeue();
                List<Cell> neighbors = GetNeighbors(current);
                for (int i = 0; i < neighbors.Count; i++)
                {
                    Cell neighbor = neighbors[i];
                    if (!unvisited.Remove(neighbor))
                    {
                        continue;
                    }

                    queue.Enqueue(neighbor);
                    component.Add(neighbor);
                }
            }

            components.Add(component);
        }

        return components;
    }

    private static void AddPathCandidate(List<Cell> path, List<PathCandidate> candidates, HashSet<string> seenKeys)
    {
        string key = BuildPathKey(path);
        if (!seenKeys.Add(key))
        {
            return;
        }

        candidates.Add(new PathCandidate
        {
            Cells = new List<Cell>(path),
            CellSet = new HashSet<Cell>(path)
        });
    }

    private static bool CandidateFitsCurrentLengthWindow(
        GenerationContext context,
        int remainingCellCount,
        int remainingPathCount,
        PathCandidate candidate)
    {
        int minLength = Math.Max(context.MinArrowLength, remainingCellCount - Math.Max(0, remainingPathCount - 1) * context.MaxArrowLength);
        int maxLength = Math.Min(context.MaxArrowLength, remainingCellCount - Math.Max(0, remainingPathCount - 1) * context.MinArrowLength);
        return candidate.Cells.Count >= minLength && candidate.Cells.Count <= maxLength;
    }

    private static bool PathHasAnyLegalTipDirection(GenerationContext context, PathCandidate path)
    {
        List<Cell> leaves = GetPathLeaves(path);
        for (int leafIndex = 0; leafIndex < leaves.Count; leafIndex++)
        {
            Cell leaf = leaves[leafIndex];
            for (int directionIndex = 0; directionIndex < Directions.Length; directionIndex++)
            {
                if (!ExitRayIntersectsCells(leaf, Directions[directionIndex], path.CellSet, context.BoardWidth, context.BoardHeight))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static HashSet<Cell> RemoveCandidateCells(HashSet<Cell> freeCells, PathCandidate candidate)
    {
        HashSet<Cell> remainingCells = new HashSet<Cell>(freeCells);
        for (int i = 0; i < candidate.Cells.Count; i++)
        {
            if (!remainingCells.Remove(candidate.Cells[i]))
            {
                return null;
            }
        }

        return remainingCells;
    }

    private static bool ArmsOnlyIntersectAtPivot(List<Cell> firstArm, List<Cell> secondArm)
    {
        HashSet<Cell> firstCells = new HashSet<Cell>(firstArm);
        for (int i = 1; i < secondArm.Count; i++)
        {
            if (firstCells.Contains(secondArm[i]))
            {
                return false;
            }
        }

        return true;
    }

    private static List<PathCandidate> CloneAndAssignPathIds(List<PathCandidate> paths)
    {
        List<PathCandidate> clones = new List<PathCandidate>();
        for (int i = 0; i < paths.Count; i++)
        {
            PathCandidate source = paths[i];
            clones.Add(new PathCandidate
            {
                Id = i + 1,
                Cells = new List<Cell>(source.Cells),
                CellSet = new HashSet<Cell>(source.CellSet)
            });
        }

        return clones;
    }

    private static List<Cell> GetPathLeaves(PathCandidate path)
    {
        List<Cell> leaves = new List<Cell>();
        if (path.Cells == null || path.Cells.Count == 0)
        {
            return leaves;
        }

        leaves.Add(path.Cells[0]);
        Cell last = path.Cells[path.Cells.Count - 1];
        if (last != path.Cells[0])
        {
            leaves.Add(last);
        }

        return leaves;
    }

    private static HashSet<int> FindBlockingArrowIds(
        GenerationContext context,
        List<PathCandidate> paths,
        int blockedArrowId,
        Cell tipCell,
        ArrowDirection direction)
    {
        HashSet<int> blockers = new HashSet<int>();
        Cell directionVector = DirectionToVector(direction);
        Cell cursor = tipCell + directionVector;

        while (IsInsideBoard(cursor, context.BoardWidth, context.BoardHeight))
        {
            if (context.ShouldStop())
            {
                return blockers;
            }

            for (int i = 0; i < paths.Count; i++)
            {
                if (context.ShouldStop())
                {
                    return blockers;
                }

                PathCandidate path = paths[i];
                if (path.Id == blockedArrowId)
                {
                    continue;
                }

                if (path.CellSet.Contains(cursor))
                {
                    blockers.Add(path.Id);
                }
            }

            cursor += directionVector;
        }

        return blockers;
    }

    private static bool ExitRayIntersectsCells(Cell tipCell, ArrowDirection direction, HashSet<Cell> cells, int boardWidth, int boardHeight)
    {
        Cell directionVector = DirectionToVector(direction);
        if (directionVector == Cell.Zero)
        {
            return false;
        }

        Cell cursor = tipCell + directionVector;
        while (IsInsideBoard(cursor, boardWidth, boardHeight))
        {
            if (cells.Contains(cursor))
            {
                return true;
            }

            cursor += directionVector;
        }

        return false;
    }

    private static List<Cell> GetFreeUnusedNeighbors(Cell cell, HashSet<Cell> freeCells, HashSet<Cell> usedCells)
    {
        List<Cell> result = new List<Cell>();
        List<Cell> neighbors = GetNeighbors(cell);
        for (int i = 0; i < neighbors.Count; i++)
        {
            Cell neighbor = neighbors[i];
            if (!freeCells.Contains(neighbor))
            {
                continue;
            }

            if (usedCells != null && usedCells.Contains(neighbor))
            {
                continue;
            }

            result.Add(neighbor);
        }

        return result;
    }

    private static int CountFreeNeighbors(Cell cell, HashSet<Cell> freeCells, HashSet<Cell> ignoredCells)
    {
        int count = 0;
        List<Cell> neighbors = GetNeighbors(cell);
        for (int i = 0; i < neighbors.Count; i++)
        {
            Cell neighbor = neighbors[i];
            if (!freeCells.Contains(neighbor))
            {
                continue;
            }

            if (ignoredCells != null && ignoredCells.Contains(neighbor))
            {
                continue;
            }

            count++;
        }

        return count;
    }

    private static List<Cell> GetNeighbors(Cell cell)
    {
        return new List<Cell>
        {
            new Cell(cell.X + 1, cell.Y),
            new Cell(cell.X - 1, cell.Y),
            new Cell(cell.X, cell.Y + 1),
            new Cell(cell.X, cell.Y - 1)
        };
    }

    private static void SortPathCandidates(List<PathCandidate> candidates, SearchState state, GenerationContext context)
    {
        int remainingCells = state.FreeCells.Count;
        int remainingPaths = context.TargetArrowCount - state.PlacedPaths.Count;
        float preferredLength = remainingPaths <= 0 ? context.MaxArrowLength : remainingCells / (float)remainingPaths;

        candidates.Sort((a, b) =>
        {
            int aScore = PathCandidateScore(a, preferredLength);
            int bScore = PathCandidateScore(b, preferredLength);
            int scoreCompare = aScore.CompareTo(bScore);
            if (scoreCompare != 0)
            {
                return scoreCompare;
            }

            return b.Cells.Count.CompareTo(a.Cells.Count);
        });
    }

    private static int PathCandidateScore(PathCandidate candidate, float preferredLength)
    {
        int lengthPenalty = Mathf.RoundToInt(Mathf.Abs(candidate.Cells.Count - preferredLength) * 100f);
        int turnBonus = CountTurns(candidate.Cells) * 8;
        return lengthPenalty - turnBonus;
    }

    private static void SortDirectionOptions(List<DirectionOption> options, bool firstAssignment)
    {
        options.Sort((a, b) =>
        {
            if (firstAssignment)
            {
                int edgeCompare = DirectionExitDistance(a).CompareTo(DirectionExitDistance(b));
                if (edgeCompare != 0)
                {
                    return edgeCompare;
                }
            }
            else
            {
                int blockerPresenceCompare = HasBlockers(b).CompareTo(HasBlockers(a));
                if (blockerPresenceCompare != 0)
                {
                    return blockerPresenceCompare;
                }
            }

            int blockerCountCompare = a.BlockerIds.Count.CompareTo(b.BlockerIds.Count);
            if (blockerCountCompare != 0)
            {
                return blockerCountCompare;
            }

            return a.Direction.CompareTo(b.Direction);
        });
    }

    private static int HasBlockers(DirectionOption option)
    {
        return option.BlockerIds.Count > 0 ? 1 : 0;
    }

    private static int DirectionExitDistance(DirectionOption option)
    {
        return option.BlockerIds.Count == 0 ? 0 : 1;
    }

    private static int CountTurns(List<Cell> path)
    {
        int turns = 0;
        for (int i = 2; i < path.Count; i++)
        {
            Cell previousDelta = path[i - 1] - path[i - 2];
            Cell currentDelta = path[i] - path[i - 1];
            if (previousDelta.X != currentDelta.X || previousDelta.Y != currentDelta.Y)
            {
                turns++;
            }
        }

        return turns;
    }

    private static List<Cell> ToSortedCells(HashSet<Cell> cells)
    {
        List<Cell> sortedCells = new List<Cell>(cells);
        sortedCells.Sort(CompareCells);
        return sortedCells;
    }

    private static List<GridPositionData> ToGridPositions(List<Cell> cells)
    {
        List<GridPositionData> positions = new List<GridPositionData>();
        for (int i = 0; i < cells.Count; i++)
        {
            positions.Add(new GridPositionData(cells[i].X, cells[i].Y));
        }

        return positions;
    }

    private static string BuildPathKey(List<Cell> path)
    {
        string forward = BuildSequenceKey(path, false);
        string reverse = BuildSequenceKey(path, true);
        return string.CompareOrdinal(forward, reverse) <= 0 ? forward : reverse;
    }

    private static string BuildSequenceKey(List<Cell> path, bool reverse)
    {
        StringBuilder builder = new StringBuilder();
        if (reverse)
        {
            for (int i = path.Count - 1; i >= 0; i--)
            {
                AppendCellKey(builder, path[i]);
            }
        }
        else
        {
            for (int i = 0; i < path.Count; i++)
            {
                AppendCellKey(builder, path[i]);
            }
        }

        return builder.ToString();
    }

    private static void AppendCellKey(StringBuilder builder, Cell cell)
    {
        builder.Append(cell.X);
        builder.Append(',');
        builder.Append(cell.Y);
        builder.Append(';');
    }

    private static Cell FirstCell(HashSet<Cell> cells)
    {
        foreach (Cell cell in cells)
        {
            return cell;
        }

        return Cell.Zero;
    }

    private static bool IsInsideBoard(Cell cell, int boardWidth, int boardHeight)
    {
        return cell.X >= 0 && cell.X < boardWidth && cell.Y >= 0 && cell.Y < boardHeight;
    }

    private static int ManhattanDistance(Cell a, Cell b)
    {
        return Math.Abs(a.X - b.X) + Math.Abs(a.Y - b.Y);
    }

    private static int DistanceToBoardEdge(Cell cell, int boardWidth, int boardHeight)
    {
        int left = cell.X;
        int right = boardWidth - 1 - cell.X;
        int bottom = cell.Y;
        int top = boardHeight - 1 - cell.Y;
        return Math.Min(Math.Min(left, right), Math.Min(bottom, top));
    }

    private static int CeilDiv(int value, int divisor)
    {
        return divisor <= 0 ? 0 : (value + divisor - 1) / divisor;
    }

    private static int CompareCells(Cell a, Cell b)
    {
        int yCompare = a.Y.CompareTo(b.Y);
        return yCompare != 0 ? yCompare : a.X.CompareTo(b.X);
    }

    private static Cell DirectionToVector(ArrowDirection direction)
    {
        switch (direction)
        {
            case ArrowDirection.Up:
                return new Cell(0, 1);
            case ArrowDirection.Down:
                return new Cell(0, -1);
            case ArrowDirection.Left:
                return new Cell(-1, 0);
            case ArrowDirection.Right:
                return new Cell(1, 0);
            default:
                return Cell.Zero;
        }
    }

    private static void Shuffle<T>(List<T> list, System.Random random)
    {
        for (int i = list.Count - 1; i > 0; i--)
        {
            int swapIndex = random.Next(i + 1);
            T temp = list[i];
            list[i] = list[swapIndex];
            list[swapIndex] = temp;
        }
    }

    private static void LogFailure(GenerationContext context)
    {
        string reason = string.IsNullOrWhiteSpace(context.FailureReason)
            ? "unknown failure"
            : context.FailureReason;

        string timeLimit = context.MaxGenerationSeconds <= 0f
            ? "unlimited"
            : $"{context.MaxGenerationSeconds:0.##}s";
        string requestedTimeLimit = context.RequestedMaxGenerationSeconds <= 0f
            ? "unlimited"
            : $"{context.RequestedMaxGenerationSeconds:0.##}s";
        string searchLimit = context.MaxSearchFrames <= 0
            ? "unlimited"
            : context.MaxSearchFrames.ToString();

        Debug.LogWarning($"Path-cover level generation failed: {reason}. Tried arrow count range: {context.EffectiveMinArrowCount}-{context.EffectiveMaxArrowCount}. Search frames: {context.SearchFrames}. Greedy attempts: {context.GreedyAttempts}. Direction frames: {context.DirectionSearchFrames}. Candidate checks: {context.CandidateChecks}. Time limit: {timeLimit} requested: {requestedTimeLimit}. Search-frame limit: {searchLimit}. Elapsed: {context.Stopwatch.Elapsed.TotalSeconds:0.00}s.");
    }

    private class GenerationContext
    {
        public int BoardWidth;
        public int BoardHeight;
        public int RequestedMinArrowCount;
        public int RequestedMaxArrowCount;
        public int EffectiveMinArrowCount;
        public int EffectiveMaxArrowCount;
        public int TargetArrowCount;
        public int MinArrowLength;
        public int MaxArrowLength;
        public int Lives;
        public int Seed;
        public int RequestedMaxSearchFrames;
        public int MaxSearchFrames;
        public int MaxCandidatesPerState;
        public int MaxPivotArms;
        public int MaxGreedyAttemptsPerArrowCount;
        public float RequestedMaxGenerationSeconds;
        public float MaxGenerationSeconds;
        public int SearchFrames;
        public int GreedyAttempts;
        public int DirectionSearchFrames;
        public int CandidateChecks;
        public string FailureReason;
        public HashSet<Cell> ShapeCells;
        public System.Random Random;
        public System.Diagnostics.Stopwatch Stopwatch;

        public bool ShouldStop()
        {
            if (MaxSearchFrames > 0 && SearchFrames >= MaxSearchFrames)
            {
                FailureReason = "search limit reached";
                return true;
            }

            if (MaxGenerationSeconds > 0f && Stopwatch.Elapsed.TotalSeconds >= MaxGenerationSeconds)
            {
                FailureReason = "generation time limit reached";
                return true;
            }

            return false;
        }

        public bool Fail(string reason)
        {
            FailureReason = reason;
            return false;
        }

        public bool ShouldRunBacktrackingSearch()
        {
            if (BoardWidth <= 8 && ShapeCells.Count <= 72)
            {
                return true;
            }

            if (TargetArrowCount <= 10 && ShapeCells.Count <= 96)
            {
                return true;
            }

            return false;
        }
    }

    private class SearchState
    {
        public HashSet<Cell> FreeCells;
        public List<PathCandidate> PlacedPaths;
    }

    private class PathCandidate
    {
        public int Id;
        public List<Cell> Cells;
        public HashSet<Cell> CellSet;
    }

    private class DirectionOption
    {
        public Cell TipCell;
        public ArrowDirection Direction;
        public HashSet<int> BlockerIds;
    }

    private class DirectionAssignment
    {
        public int ArrowId;
        public Cell TipCell;
        public ArrowDirection Direction;
        public HashSet<int> BlockerIds;
    }

    private class RuntimeArrow
    {
        public int Id;
        public List<Cell> PathCells;
        public HashSet<Cell> CellSet;
        public Cell TipCell;
        public ArrowDirection Direction;
    }

    private class DependencyGraph
    {
        private readonly Dictionary<int, HashSet<int>> edgesBySource = new Dictionary<int, HashSet<int>>();

        public int NodeCount => edgesBySource.Count;

        public void AddNode(int arrowId)
        {
            if (!edgesBySource.ContainsKey(arrowId))
            {
                edgesBySource.Add(arrowId, new HashSet<int>());
            }
        }

        public void AddEdge(int blockerArrowId, int blockedArrowId)
        {
            AddNode(blockerArrowId);
            AddNode(blockedArrowId);

            if (blockerArrowId == blockedArrowId)
            {
                return;
            }

            edgesBySource[blockerArrowId].Add(blockedArrowId);
        }

        public DependencyGraph Clone()
        {
            DependencyGraph clone = new DependencyGraph();
            foreach (KeyValuePair<int, HashSet<int>> entry in edgesBySource)
            {
                clone.AddNode(entry.Key);
                foreach (int blockedArrowId in entry.Value)
                {
                    clone.AddEdge(entry.Key, blockedArrowId);
                }
            }

            return clone;
        }

        public bool IsAcyclic()
        {
            return TopologicalSort().Count == NodeCount;
        }

        public List<int> TopologicalSort()
        {
            Dictionary<int, int> indegreeByArrowId = new Dictionary<int, int>();
            foreach (int arrowId in edgesBySource.Keys)
            {
                indegreeByArrowId[arrowId] = 0;
            }

            foreach (KeyValuePair<int, HashSet<int>> entry in edgesBySource)
            {
                foreach (int blockedArrowId in entry.Value)
                {
                    if (!indegreeByArrowId.ContainsKey(blockedArrowId))
                    {
                        indegreeByArrowId[blockedArrowId] = 0;
                    }

                    indegreeByArrowId[blockedArrowId]++;
                }
            }

            List<int> ready = new List<int>();
            foreach (KeyValuePair<int, int> entry in indegreeByArrowId)
            {
                if (entry.Value == 0)
                {
                    ready.Add(entry.Key);
                }
            }

            ready.Sort();
            List<int> result = new List<int>();
            while (ready.Count > 0)
            {
                int arrowId = ready[0];
                ready.RemoveAt(0);
                result.Add(arrowId);

                if (!edgesBySource.TryGetValue(arrowId, out HashSet<int> blockedArrows))
                {
                    continue;
                }

                List<int> sortedBlockedArrows = new List<int>(blockedArrows);
                sortedBlockedArrows.Sort();
                for (int i = 0; i < sortedBlockedArrows.Count; i++)
                {
                    int blockedArrowId = sortedBlockedArrows[i];
                    indegreeByArrowId[blockedArrowId]--;
                    if (indegreeByArrowId[blockedArrowId] == 0)
                    {
                        ready.Add(blockedArrowId);
                        ready.Sort();
                    }
                }
            }

            return result;
        }

        public List<DependencyData> ToDependencyData()
        {
            List<DependencyData> dependencies = new List<DependencyData>();
            foreach (KeyValuePair<int, HashSet<int>> entry in edgesBySource)
            {
                foreach (int blockedArrowId in entry.Value)
                {
                    dependencies.Add(new DependencyData(entry.Key, blockedArrowId));
                }
            }

            dependencies.Sort((a, b) =>
            {
                int blockerCompare = a.blockerArrowId.CompareTo(b.blockerArrowId);
                return blockerCompare != 0 ? blockerCompare : a.blockedArrowId.CompareTo(b.blockedArrowId);
            });
            return dependencies;
        }
    }

    private struct Cell : IEquatable<Cell>
    {
        public static readonly Cell Zero = new Cell(0, 0);

        public readonly int X;
        public readonly int Y;

        public Cell(int x, int y)
        {
            X = x;
            Y = y;
        }

        public bool Equals(Cell other)
        {
            return X == other.X && Y == other.Y;
        }

        public override bool Equals(object obj)
        {
            return obj is Cell other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return (X * 397) ^ Y;
            }
        }

        public static bool operator ==(Cell left, Cell right)
        {
            return left.Equals(right);
        }

        public static bool operator !=(Cell left, Cell right)
        {
            return !left.Equals(right);
        }

        public static Cell operator +(Cell left, Cell right)
        {
            return new Cell(left.X + right.X, left.Y + right.Y);
        }

        public static Cell operator -(Cell left, Cell right)
        {
            return new Cell(left.X - right.X, left.Y - right.Y);
        }
    }
}
